name          'mtbvang-devhost'
version       '0.1.0'
source        'https://github.com/mtbvang/puppet-devhost.git'
author        'Vang Nguyen <mtb.vang@gmail.com>'
license       'Apache 2.0'
summary       'Common library of puppet manifests used by other puppet modules.'
description   ''
project_page  'https://github.com/mtbvang/puppet-devhost'

dependency 'puppetlabs/stdlib', '>= 1.0.0'
dependency 'puppetlabs/apt', '1.6.0'
dependency 'mtbvang/mtbvang', '0.1.0'
dependency 'leonardothibes/wget', '1.0.4'
dependency 'saz/ssh', '2.4.0'
dependency 'opentable/puppetversion', '1.0.0'
dependency 'ploperations/bundler', '1.0.1'
dependency 'garethr/docker'
dependency 'runthebusiness/eclipse'
dependency 'mtbvang/devpuppet'