name          'mtbvang-devhost'
version       '0.1.0'
source        'https://github.com/mtbvang/puppet-common.git'
author        'Vang Nguyen <mtb.vang@gmail.com>'
license       'Apache 2.0'
summary       'Common library of puppet manifests used by other puppet modules.'
description   ''
project_page  'https://github.com/mtbvang/puppet-common'

dependency 'puppetlabs-stdlib', '>= 1.0.0'
dependency 'leonardothibes-wget', '>= 1.0.4'
dependency 'puppetlabs-apt', '>= 1.6.0'
